Ft domain skeleton
2011-fakebook-project3/notifications pull request #16
Opened 2021-01-04 21:32 UTC by JordanEGarcia

2021-01-04 22:03 UTC, mendac017 requested changes
There should be tests for domain methods that fail.

2021-01-04 22:03 UTC, mendac017 commented on FakebookNotifications/FakebookNotifications.Domain/Models/User.cs
> +            return !(string.IsNullOrEmpty(Id) || string.IsNullOrEmpty(Email));
We don't want implementation in this PR. Instead have it throw not implemented for all methods.

2021-01-04 22:14 UTC, mendac017 commented
The docker build also failed in the pipeline.

2021-01-06 16:36 UTC, mendac017 approved these changes
This looks good. I tested it and the tests do fail.

2021-01-06 16:38 UTC, mattmarnien approved these changes

2021-01-06 16:43 UTC, townerr requested changes

2021-01-06 16:43 UTC, townerr commented on FakebookNotifications/FakebookNotifications.Domain/Models/User.cs
> +
fix brace formatting

2021-01-06 16:43 UTC, townerr commented on FakebookNotifications/FakebookNotifications.Testing/FakebookNotifications.Testing.csproj
>  	<ItemGroup>
item group tabbed in too far

2021-01-06 16:43 UTC, townerr commented on FakebookNotifications/FakebookNotifications.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "FakebookNotifications.Domain", "FakebookNotifications.Domain\FakebookNotifications.Domain.csproj", "{10727CC8-E023-4F66-8510-151B65218FD0}"
end project for this

2021-01-06 17:40 UTC, townerr approved these changes

2021-01-06 18:16 UTC, RevatureGentry approved these changes

2021-01-06 18:18 UTC, merged