Add dockerfile
2011-fakebook-project3/notifications pull request #5
Opened 2020-12-29 21:09 UTC by mattmarnien

2020-12-29 21:11 UTC, mendac017 approved these changes
Glad we added the .dockerignore

2020-12-29 21:12 UTC, townerr approved these changes

2020-12-29 21:28 UTC, escalonn requested changes
dockerfile is very basic, doesn't even build the code; not ready for main branch. should use multi-stage build

2020-12-29 21:51 UTC, escalonn requested changes
if you'd tested this, it would have failed twice over. you should catch this before it comes to me

2020-12-29 21:51 UTC, escalonn commented on Dockerfile
> +RUN dotnet public -c Release -o publish
dotnet public

2020-12-29 21:51 UTC, escalonn commented on Dockerfile
> +FROM mcr.microsoft.com/dotnet/sdk:5.0 AS runtime
don't use the sdk image for the final base image

2020-12-29 21:51 UTC, escalonn commented on Dockerfile
> +RUN dotnet restore
need to copy sln and csprojs, to correct places

2020-12-29 23:07 UTC, townerr approved these changes

2020-12-29 23:49 UTC, mendac017 commented
I was able to test it on my local environment and got a response from /weatherforecast

2020-12-30 15:56 UTC, escalonn requested changes
seems like the only files the dockerfile needs are down in fakebooknotifications directory. expect the build context to be that directory. move the dockerignore down there and also the dockerfile if you prefer.
if the build context is up at repo root, `.git` also needs to be dockerignored, but it's not an issue if the context moves down.

2020-12-30 15:56 UTC, escalonn commented on Dockerfile
> +RUN dotnet publish -c Release -o publish
publish the startup project specifically

2020-12-30 16:30 UTC, escalonn approved these changes

2020-12-30 16:32 UTC, merged